### ISSUE TITLE
Bugs under Python 3

### ISSUE THREAD

**Issue by ZeweiChu** [inikdom/opensubtitles-parser#7]
The code does not run with Python 3. I got the following error:

> Error in OpenSubtitles/en/Action/1982/3182_58119_74046_tron.xml
> Processing OpenSubtitles/en/Action/1982/905_41278_50921_conan_the_barbarian.xml...
> a bytes-like object is required, not 'str'

Maybe we can this in README file, that the code only runs on Python 2.7.

**Comment by domerin0** [comment]
Hey that's a great suggestion. I've updated the readme to reflect this. I have been planning to update all my python 2.7 projects to python 3,  but I have no timeline for it yet.
